In [1]:
# Importing the required package

import numpy as np

In [2]:
NP1 = np.array([1,2,3,4])
print(NP1)              # Printing the numpy array
print(type(NP1))        # Type of the numpy array

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
NP2 = np.array([[1,2,3],[4,5,6]])
print(NP2)              # Printing the numpy array
print(type(NP2))        # Type of the numpy array
print(NP2.shape)        # Shape of the numpy array
print(NP2.size)         # Size of the numpy array - '2*3=6'
print(NP2.ndim)         # Number of dimensions of the numpy array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2


In [10]:
# Printing the element(s) at specific location
# 1-D Array

print(NP1)
print(NP1[2])           # Element at index '2'
print(NP1[0:2])         # Elements from start-index to end-index
print(NP1[:1])

[1 2 3 4]
3
[1 2]
[1]


In [18]:
# Printing the entire 2D array NP2
print(NP2)

# Printing the first row of the 2D array (index 0)
print(NP2[0])

# Printing the element at the first row, second column (index 0,1)
print(NP2[0][1])

# Same as above, using the comma notation to index (first row, third column)
print(NP2[0,2])

# Slicing the 2D array to get all rows, but only the third column (index 2)
print(NP2[:,2])

# Slicing the 2D array to get the first row (index 0) across all columns
print(NP2[0,:])

# Accessing the element at row 1, column 1 (index 1,1)
print(NP2[1,1])

# Printing the entire 2D array again (same as the first line)
print(NP2[:,:])

# Slicing a subarray from rows 0 to 2, and columns 1 to 3 (excluding row 2 and column 3)
print(NP2[0:2,1:3])


[[1 2 3]
 [4 5 6]]
[1 2 3]
2
3
[3 6]
[1 2 3]
5
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [23]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

**Element-wise Operations**

In [24]:
# Element-wise Addition
print("Element-wise Addition:")
print(arr1 + arr2)  # Output: [5 7 9]

# Element-wise Subtraction
print("\nElement-wise Subtraction:")
print(arr1 - arr2)  # Output: [-3 -3 -3]

# Element-wise Multiplication
print("\nElement-wise Multiplication:")
print(arr1 * arr2)  # Output: [ 4 10 18]

# Element-wise Division
print("\nElement-wise Division:")
print(arr1 / arr2)  # Output: [0.25 0.4 0.5]

# Element-wise Power
print("\nElement-wise Power:")
print(arr1 ** arr2)  # Output: [  1  32 729]

# Element-wise Modulus
print("\nElement-wise Modulus (arr2 % arr1):")
print(arr2 % arr1)  # Output: [0 1 0]

Element-wise Addition:
[5 7 9]

Element-wise Subtraction:
[-3 -3 -3]

Element-wise Multiplication:
[ 4 10 18]

Element-wise Division:
[0.25 0.4  0.5 ]

Element-wise Power:
[  1  32 729]

Element-wise Modulus (arr2 % arr1):
[0 1 0]


**Scalar Operations**



In [25]:
# Scalar Operations
print("\nScalar Addition (add 10 to each element of arr1):")
print(arr1 + 10)  # Output: [11 12 13]

print("\nScalar Multiplication (multiply arr2 by 2):")
print(arr2 * 2)  # Output: [ 8 10 12]


Scalar Addition (add 10 to each element of arr1):
[11 12 13]

Scalar Multiplication (multiply arr2 by 2):
[ 8 10 12]


**Matrix Operations**

In [26]:
# Matrix Operations (2D Arrays)
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

# Matrix Addition
print("\nMatrix Addition:")
print(arr1_2d + arr2_2d)  # Output: [[ 6  8] [10 12]]

# Matrix Multiplication (element-wise)
print("\nMatrix Element-wise Multiplication:")
print(arr1_2d * arr2_2d)  # Output: [[ 5 12] [21 32]]

# Matrix Division (element-wise)
print("\nMatrix Element-wise Division:")
print(arr1_2d / arr2_2d)  # Output: [[0.2 0.33333333] [0.42857143 0.5]]

# 9. Universal Functions (ufuncs)
print("\nSine of each element in arr1:")
print(np.sin(arr1))  # Output: [ 0.84147098  0.90929743  0.14112001]

print("\nExponential of each element in arr1:")
print(np.exp(arr1))  # Output: [  2.71828183   7.3890561   20.08553692]


Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Sine of each element in arr1:
[0.84147098 0.90929743 0.14112001]

Exponential of each element in arr1:
[ 2.71828183  7.3890561  20.08553692]


In [27]:
# Perform matrix multiplication using the '@' operator
print(arr1_2d@arr2_2d)

[[19 22]
 [43 50]]
