In [3]:
#NumPy Basics
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
#Create numpy array
import numpy as np
sales=np.array([10,85,62,32,78,96])
print(sales)
print(type(sales))
print(sales.dtype)

[10 85 62 32 78 96]
<class 'numpy.ndarray'>
int32


In [10]:
arr=np.ones(5,dtype='int')
print(arr)
arr=np.zeros(5,dtype='int')
print(arr)

[1 1 1 1 1]
[0 0 0 0 0]


In [16]:
arr=np.arange(10,20)
print(arr)
print(arr[3])
print("No of Dim:",arr.ndim)

[10 11 12 13 14 15 16 17 18 19]
13
No of Dim: 1


In [2]:
import numpy as np
arr=np.linspace(10,50,5)
print(arr)

[10. 20. 30. 40. 50.]


In [18]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print("No of Dim:",arr.ndim)
print("No of elements:",arr.size)
print("Shape of array:",arr.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
No of Dim: 2
No of elements: 9
Shape of array: (3, 3)


In [6]:
#Reshaping of array
arr=np.array([10,20,30,40,50,60])
arr_new=arr.reshape(2,3)
print(arr_new)

[[10 20 30]
 [40 50 60]]


In [10]:
#Fancy indexing
print(arr[0]) #normal Indexing
ind=np.array([[3,4],[1,2]])
print(arr[ind])

10
[[40 50]
 [20 30]]


In [12]:
#Broadcasting
lst=[10,20,30]
print(lst*3)
arr=np.array(lst)
print(arr*3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]
[30 60 90]
