In [1]:
import numpy as np
import random

In [4]:
l = [1,2,3]
la = np.array(l)
print(la)
print(type(la))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
ma = np.array(matrix)
print(ma)
print(type(ma))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((6,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(3) #generates random numbers from a uniform distribution over the range [0, 1)

array([0.12264983, 0.47854069, 0.94623717])

In [19]:
np.random.rand(4,5)

array([[0.15305573, 0.68850545, 0.20471199, 0.04255344, 0.37282423],
       [0.34949958, 0.38753044, 0.91797444, 0.00589566, 0.8289641 ],
       [0.32267334, 0.33084758, 0.2521151 , 0.9397098 , 0.16851238],
       [0.45493677, 0.07204113, 0.80961039, 0.42706482, 0.61992493]])

In [20]:
np.random.randn(4) #generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

array([ 0.23740361, -0.38990085,  0.8424428 , -1.0863272 ])

In [21]:
np.random.randint(1,10)

1

In [25]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr = np.arange(1,25)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.max()

24

In [32]:
arr.argmax()

23

In [33]:
arr.min()

1

In [34]:
arr.argmin()

0

In [35]:
arr.shape


(24,)

In [37]:
arr.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,24).shape

(1, 24)

In [40]:
arr.reshape(24,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arr.dtype

dtype('int32')

In [42]:
arr[0:6] = 34

In [43]:
arr

array([34, 34, 34, 34, 34, 34,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [44]:
arra = arr.copy()

In [45]:
arra

array([34, 34, 34, 34, 34, 34,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [46]:
arr[:] = 55

In [47]:
arr

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55])

In [49]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [54]:
arr2d[2]

array([35, 40, 45])

In [55]:
arr2d[1,2]

30

In [58]:
arr2d1 = np.zeros((10,10))
arr2d1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
print(arr2d1.shape[0])
print(arr2d1.shape[1])

10
10


In [63]:
for i in range(arr2d1.shape[1]):
    arr2d1[i] = i
arr2d1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [79]:
arr2d2 = np.array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])
arr2d2[[2,5,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [80]:
arr2d2[[8,7,6,5]]

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [82]:
arr2d2[arr2d2 > 3]

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [83]:
arr2d2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [85]:
#Operations


In [86]:
arr2d2 + arr2d2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.]])

In [87]:
arr2d2 - arr2d2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
arr2d2 * arr2d2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [25., 25., 25., 25., 25., 25., 25., 25., 25., 25.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [49., 49., 49., 49., 49., 49., 49., 49., 49., 49.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [81., 81., 81., 81., 81., 81., 81., 81., 81., 81.]])

In [89]:
arr2d2 / arr2d2

C:\Users\srirajax\AppData\Local\Temp\ipykernel_17596\1142294941.py:1: RuntimeWarning: invalid value encountered in divide
  arr2d2 / arr2d2


array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [92]:
1/arr2d2

C:\Users\srirajax\AppData\Local\Temp\ipykernel_17596\768489197.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2d2


array([[       inf,        inf,        inf,        inf,        inf,
               inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ,
        0.25      , 0.25      , 0.25      , 0.25      , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       , 0.2       ],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
        0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.14285714, 0.14285714, 0.1428571

In [93]:
arr2d2 ** 3

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.],
       [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
       [ 64.,  64.,  64.,  64.,  64.,  64.,  64.,  64.,  64.,  64.],
       [125., 125., 125., 125., 125., 125., 125., 125., 125., 125.],
       [216., 216., 216., 216., 216., 216., 216., 216., 216., 216.],
       [343., 343., 343., 343., 343., 343., 343., 343., 343., 343.],
       [512., 512., 512., 512., 512., 512., 512., 512., 512., 512.],
       [729., 729., 729., 729., 729., 729., 729., 729., 729., 729.]])

In [94]:
#Universal array functions

In [97]:
arr2d2 = arr2d2[[2,4,5,6]]
np.sqrt(arr2d2)

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356,
        1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798,
        2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974,
        2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [98]:
np.exp(arr2d2)

array([[  7.3890561 ,   7.3890561 ,   7.3890561 ,   7.3890561 ,
          7.3890561 ,   7.3890561 ,   7.3890561 ,   7.3890561 ,
          7.3890561 ,   7.3890561 ],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003,
         54.59815003,  54.59815003,  54.59815003,  54.59815003,
         54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ,
        148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ,
        148.4131591 , 148.4131591 ],
       [403.42879349, 403.42879349, 403.42879349, 403.42879349,
        403.42879349, 403.42879349, 403.42879349, 403.42879349,
        403.42879349, 403.42879349]])

In [99]:
#Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [101]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [102]:
arr2d.sum(axis=0) #Column sum

array([60, 75, 90])

In [103]:
arr2d.sum(axis=1) #row sum

array([ 30,  75, 120])